[package]
name = "tower-defense"
version = "0.0.0"
edition = "2024"
description = "Middleware utilities to authenticate RPC calls using libp2p node keys"
license = "Apache-2.0 OR (GPL-3.0-or-later WITH Classpath-exception-2.0)"
repository = "https://github.com/Mosaic-Chain/tower-defense"

[dependencies]
