[package]
name = "tower-defense"
version = "0.2.1"
edition = "2024"
description = "Middleware utilities to authenticate RPC calls using libp2p node keys"
license = "Apache-2.0 OR (GPL-3.0-or-later WITH Classpath-exception-2.0)"
repository = "https://github.com/Mosaic-Chain/tower-defense"

[dependencies]
bs58 = { version = "0.5.1" }
ed25519-dalek = { version = "2.2.0", features = ["serde"] }
jsonrpsee = { version = "0.26.0", features = ["client", "server"] }
multihash = { version = "0.19.3" }
quick-protobuf = { version = "0.8.1" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145" }
sha2 = { version = "0.10.9" }
thiserror = { version = "2.0.17" }

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt"] }
hex = { version = "0.4.3" }
